apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: all-in-one-server-dev
    stage: dev
    tbn_cluster: all-in-one-server
    version: my-local-copy
  name: all-in-one-server-dev
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: all-in-one-server-dev
      stage: dev
      tbn_cluster: all-in-one-server
      version: my-local-copy
  template:
    metadata:
      labels:
        run: all-in-one-server-dev
        stage: dev
        tbn_cluster: all-in-one-server
        version: my-local-copy
    spec:
      containers:
      - env:
        - name: TBN_COLOR
          value: FDA100
        - name: TBN_NAME
          value: my-local-copy
        image: turbinelabs/all-in-one-server:0.18.0
        imagePullPolicy: IfNotPresent
        name: all-in-one-server-dev
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      restartPolicy: Always
